{{if .Values.configmap.enabled}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webapp-chart-name" . }}-configmap
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configmap.data | nindent 4 }}
{{end}}